name: Deploy Portfolio to S3

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: AKIA5GXM3PFWVO6TJ2P2
        aws-secret-access-key: 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
        aws-region: us-east-1

    - name: Sync Files to S3
      run: |
        aws s3 sync . s3://${{ secrets.S3_BUCKET }} --delete --exclude ".git/*" --exclude ".github/*"
